name = "testlokiworker"
main = "src/app/api/index.js"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "testloki"
database_id = "da2a7de2-acfa-4263-9fe9-99241c285c6b"

migrations_dir = "./src/db/migrations"

